# adapted from http://conda.pydata.org/docs/travis.html
language: python
python:
 # We don't actually use the Travis Python, but this keeps it organized.
 - "2.7"
 - "3.5"

# switch to new infrastructure
sudo: false

before_install:
 # download and install miniconda
 - wget http://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh -O miniconda.sh;
 - bash miniconda.sh -b -p $HOME/conda
 - export PATH="$HOME/conda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda config --add channels conda-forge
 - conda update -q conda

 # install essentials for deployment
 - conda install -f  setuptools
 - conda install -q conda-build
 - conda install -q anaconda-client

 # Useful for debugging any issues with conda
 - conda info -a

 # create and activate the build/test environment
 - conda create -q -n tenv python=$TRAVIS_PYTHON_VERSION pip cmake
 - source activate tenv

install:
 # Necessary dependencies
 - conda install -q matplotlib pytest

before_deploy:
- conda install -f  setuptools
- conda build conda_recipe -c local

deploy:
  # Deploy to Anaconda.org
    provider: script
    script: anaconda -t $CONDA_UPLOAD_TOKEN  upload  --skip -u NostrumBioDiscovery $HOME/conda/conda-bld/**/pele_platform-*.tar.bz2
    skip_cleanup: true
    on:
tags: true

